### ISSUE TITLE
Latest release jar is empty.

### ISSUE THREAD

**Issue by RDKRACZ** [corgi-in-tights/barrenisles#11]
Weights about 250 bytes.

**Comment by AlisterGontineac** [comment]
Ah, that's probably what is going on with version 1.0.7
Yeah doesn't show in mods, so that would be why XD

**Comment by corgi-in-tights** [comment]
whAT

**Comment by corgi-in-tights** [comment]
excuse me for a minute i need to talk with my publisher

**Comment by RDKRACZ** [comment]
@corgi-in-tights it got fixed not so while after my issue, I left it open in case someone else downloads 1.0.7 and didn't see the hotfix release.
https://www.curseforge.com/minecraft/mc-mods/barren-isles/files/all
