### ISSUE TITLE
Quicksand is a bit too op?

### ISSUE THREAD

**Issue by corgi-in-tights** [corgi-in-tights/barrenisles#8]
Need to figure out how to lower the damage, maybe lower damage depending on armor?
Unsure, need to think of solutions.

Currently takes you out in roughly 20 -30 seconds in peaceful, easy-hard however reduces that by twice over.
Christ anyone in netherite can be wiped out in a matter of seconds.

Either reduce damage or make it more breakable?

**Comment by Xyndra** [comment]
Make it like quicksand

**Comment by TrueWolfishOne** [comment]
reduce damage, making it more breakable still allows you to be easily trapped since you can fall into more

**Comment by corgi-in-tights** [comment]
i think i fixed this
reduced damage, made it so armor affects quicksand damage and sinking
